packages:
  - apps/*
  - packages/*

catalog:
  '@trpc/client': 11.8.1
  '@trpc/server': 11.8.1
  '@types/pg': ^8.16.0
  better-auth: ^1.4.9
  dotenv: ^17.2.2
  drizzle-orm: ^0.45.1
  next: ^16.1.1
  typescript: ^5
  zod: ^4.1.13
